# DataSource Config
spring:
  datasource:
    druid:
      url: jdbc:oracle:thin:@81.68.195.233:1521:helowin
      username: dev
      password: dev
  redis:
    host: localhost
    port: 6379
    password: Maserhe123456..

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379




jwt:
  #  header: Authorization
  token:         # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    #    7天
    #    expiration: 604800
    #    一天
    expiration: 86400

