# DataSource Config
spring:
  datasource:
    druid:
      url: jdbc:oracle:thin:@121.36.132.192:1521:helowin
      username: dev
      password: system
  redis:
    host: localhost
    port: 6379
  # api 加密字符
  encrypt:
    key: abcdef0123456789

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

redis:
  host: 127.0.0.1
  # Redis port
  port: 6379
  # Redis password, 没设置可以不用填写
  password:
  timeout: 10000
  # 连接池设置
  pool:
    max-active: 200
    max-wait: -1
    max-idle: 8
    min-idle: 0


jwt:
  #  header: Authorization
  token:         # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    #    7天
    #    expiration: 604800
    #    一天
    expiration: 86400
